#!/bin/bash
#
# Usage: script/run
#

set -e

docker kill pretty-slack-notify > /dev/null 2>&1 || true
docker rm   pretty-slack-notify > /dev/null 2>&1 || true
docker run \
  --rm \
  -it \
  --name pretty-slack-notify \
  -e WERCKER_STEP_ROOT=/app \
  -e WERCKER_PRETTY_SLACK_NOTIFY_WEBHOOK_URL="${WERCKER_PRETTY_SLACK_NOTIFY_WEBHOOK_URL}" \
  -e WERCKER_PRETTY_SLACK_NOTIFY_CHANNEL="${WERCKER_PRETTY_SLACK_NOTIFY_CHANNEL}" \
  -e WERCKER_GIT_OWNER="${WERCKER_GIT_OWNER}" \
  -e WERCKER_GIT_REPOSITORY="${WERCKER_GIT_REPOSITORY}" \
  -e WERCKER_APPLICATION_URL="${WERCKER_APPLICATION_URL}" \
  -e WERCKER_BUILD_URL="${WERCKER_BUILD_URL}" \
  -e WERCKER_GIT_COMMIT="${WERCKER_GIT_COMMIT}" \
  -e WERCKER_GIT_BRANCH="${WERCKER_GIT_BRANCH}" \
  -e WERCKER_STARTED_BY="${WERCKER_STARTED_BY}" \
  -e DEPLOY="${DEPLOY}" \
  -e WERCKER_DEPLOY_URL="${WERCKER_DEPLOY_URL}" \
  -e WERCKER_DEPLOYTARGET_NAME="${WERCKER_DEPLOYTARGET_NAME}" \
  -e WERCKER_RESULT="${WERCKER_RESULT}" \
  quay.io/wantedly/pretty-slack-notify
