#!/bin/bash
#
# Usage: script/test-for-ruby-box
#

set -e

IFS=$'\n'
echo "==> Loading environment variables ..."
for line in `cat .env | grep -v ^# | grep -v "^ *#"`
do
  if [ -z "${line}" ]
  then
    continue
  else
    export ${line}
  fi
done

./run.sh

if test $? -eq 0
then
  echo ""
  echo "   Test Passed"
else
  echo ""
  echo "   Test Failed"
  exit 1
fi
